### ISSUE TITLE
How to build the fonts? I'm getting a FeatureLibError

### ISSUE THREAD

**Issue by OmarIthawi** [aliftype/amiri#146]
Here's what I've tried on my Ubuntu 16.04:

```
$ sudo apt-get install python-fontforge
$ mkvirtualenv amiri --system-site-packages
$ pip install fonttools
$ make all
```

I've got the following error:

```
$ make all
   FF	Amiri-Regular.ttf
Failed to find NameList: AGL For New Fonts
Failed! Inspect temporary file: '/tmp/tmpC_0PhV'
Traceback (most recent call last):
  File "tools/build.py", line 691, in <module>
    makeDesktop(args)
  File "tools/build.py", line 670, in makeDesktop
    generateFont(options, font, fea)
  File "tools/build.py", line 183, in generateFont
    addOpenTypeFeaturesFromString(ttfont, fea)
  File "/home/omar/.virtualenvs/amiri/local/lib/python2.7/site-packages/fontTools/feaLib/builder.py", line 31, in addOpenTypeFeaturesFromString
    addOpenTypeFeatures(font, featurefile, tables=tables)
  File "/home/omar/.virtualenvs/amiri/local/lib/python2.7/site-packages/fontTools/feaLib/builder.py", line 22, in addOpenTypeFeatures
    builder.build(tables=tables)
  File "/home/omar/.virtualenvs/amiri/local/lib/python2.7/site-packages/fontTools/feaLib/builder.py", line 107, in build
    self.parseTree = Parser(self.file, self.glyphMap).parse()
  File "/home/omar/.virtualenvs/amiri/local/lib/python2.7/site-packages/fontTools/feaLib/parser.py", line 71, in parse
    statements.append(self.parse_lookup_(vertical=False))
  File "/home/omar/.virtualenvs/amiri/local/lib/python2.7/site-packages/fontTools/feaLib/parser.py", line 512, in parse_lookup_
    self.parse_block_(block, vertical)
  File "/home/omar/.virtualenvs/amiri/local/lib/python2.7/site-packages/fontTools/feaLib/parser.py", line 1393, in parse_block_
    statements.append(self.parse_lookupflag_())
  File "/home/omar/.virtualenvs/amiri/local/lib/python2.7/site-packages/fontTools/feaLib/parser.py", line 550, in parse_lookupflag_
    self.next_token_location_)
fontTools.feaLib.error.FeatureLibError: <features>:3110:25: "," is not a recognized lookupflag
Makefile:58: recipe for target 'Amiri-Regular.ttf' failed
make: *** [Amiri-Regular.ttf] Error 1
```

Any ideas how to resolve that issue?

**Comment by khaledhosny** [comment]
What the version of FontTools package, `ttx --version`?

**Comment by OmarIthawi** [comment]
@khaledhosny Looks like FontForge wasn't installed. I've installed it. However the same issue persisted.

I'm attaching the versions bellow: :point_down: 

```
$ ttx --version
usage: ttx [options] inputfile1 [... inputfileN]

    TTX 3.0 -- From OpenType To XML And Back

$ dpkg --list | grep fontforge
ii  fontforge                                  20120731.b-7.1                               amd64        font editor
ii  fontforge-common                           20120731.b-7.1                               all          font editor (common files)
ii  libfontforge1                              20120731.b-7.1                               amd64        font editor - runtime library
ii  python-fontforge                           20120731.b-7.1                               amd64        font editor - Python bindings
```

**Comment by khaledhosny** [comment]
The error comes from FontTools, FontForge GUI is not needed. It seems you have an old version of FontTools, probably the one provided by your distribution. Try updating it with `pip install -U fonttools`.

**Comment by OmarIthawi** [comment]
Thanks @khaledhosny. It looks like the latest version is installed:

```
$ pip install -U fonttools
Requirement already up-to-date: fonttools in /home/omar/.virtualenvs/amiri/lib/python2.7/site-packages

$ pip freeze | grep fonttools
fonttools==3.24.1

$ python --version
Python 2.7.12

$ pip --version
pip 9.0.3 from /home/omar/.virtualenvs/amiri/local/lib/python2.7/site-packages (python 2.7)
```
Perhaps a `fonttools` _downgrade_ is needed?

As a side note, I'm using virtualenv BTW, do you use it as well?

**Comment by khaledhosny** [comment]
That is the same version of FontTools I have here. Please attache the file mentioned in `Failed! Inspect temporary file:` message.

**Comment by OmarIthawi** [comment]
The full log is :point_down: and here's the [temp file](https://gist.github.com/OmarIthawi/ff641b64e33a8d41d3146dfeff87362f).:

```
$ workon amiri && cd ~/work/mathjax/amiri/ && make all
   FF	Amiri-Regular.ttf
Failed to find NameList: AGL For New Fonts
Failed! Inspect temporary file: '/tmp/tmp30k1gI'
Traceback (most recent call last):
  File "tools/build.py", line 691, in <module>
    makeDesktop(args)
  File "tools/build.py", line 670, in makeDesktop
    generateFont(options, font, fea)
  File "tools/build.py", line 183, in generateFont
    addOpenTypeFeaturesFromString(ttfont, fea)
  File "/home/omar/.virtualenvs/amiri/local/lib/python2.7/site-packages/fontTools/feaLib/builder.py", line 31, in addOpenTypeFeaturesFromString
    addOpenTypeFeatures(font, featurefile, tables=tables)
  File "/home/omar/.virtualenvs/amiri/local/lib/python2.7/site-packages/fontTools/feaLib/builder.py", line 22, in addOpenTypeFeatures
    builder.build(tables=tables)
  File "/home/omar/.virtualenvs/amiri/local/lib/python2.7/site-packages/fontTools/feaLib/builder.py", line 107, in build
    self.parseTree = Parser(self.file, self.glyphMap).parse()
  File "/home/omar/.virtualenvs/amiri/local/lib/python2.7/site-packages/fontTools/feaLib/parser.py", line 71, in parse
    statements.append(self.parse_lookup_(vertical=False))
  File "/home/omar/.virtualenvs/amiri/local/lib/python2.7/site-packages/fontTools/feaLib/parser.py", line 512, in parse_lookup_
    self.parse_block_(block, vertical)
  File "/home/omar/.virtualenvs/amiri/local/lib/python2.7/site-packages/fontTools/feaLib/parser.py", line 1393, in parse_block_
    statements.append(self.parse_lookupflag_())
  File "/home/omar/.virtualenvs/amiri/local/lib/python2.7/site-packages/fontTools/feaLib/parser.py", line 550, in parse_lookupflag_
    self.next_token_location_)
fontTools.feaLib.error.FeatureLibError: <features>:3110:25: "," is not a recognized lookupflag
Makefile:58: recipe for target 'Amiri-Regular.ttf' failed
make: *** [Amiri-Regular.ttf] Error 1
```

**Comment by khaledhosny** [comment]
Looks like a bug in the FontForge version you have, the line `lookupflag RightToLeft, IgnoreMarks;` should be `lookupflag RightToLeft IgnoreMarks;` without the coma after `RightToLeft`.

**Comment by OmarIthawi** [comment]
Any ideas where should I look? Perhaps downgrading the fontforge?

BTW what OS/distribution are you using?

**Comment by khaledhosny** [comment]
You need a newer version of FontForge, anything released after 2014 when this bug was fixed: https://github.com/fontforge/fontforge/commit/43961afff2e0fe442116c03454917291ad8d621d

**Comment by OmarIthawi** [comment]
Awesome, thanks @khaledhosny! I'll try that and will let you know :slightly_smiling_face:

**Comment by OmarIthawi** [comment]
@khaledhosny it works now! Thank you :)
